
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist/praxus-app
          repo: LogiLinkP/test-preview
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}